quarkus:
  grpc:
    server:
      port: 9090
      use-separate-server: false
      plain-text: false
  http:
    port: -1
    ssl-port: ${QUARKUS_HTTP_SSL_PORT:8443}
    insecure-requests: disabled
    ssl:
      client-auth: REQUIRED
    tls-configuration-name: bridge
  tls:
    bridge:
      key-store:
        pem:
          "0":
            cert: ${QUARKUS_TLS_BRIDGE_KEY_STORE_PEM_0_CERT:tls/placeholder-server.pem}
            key: ${QUARKUS_TLS_BRIDGE_KEY_STORE_PEM_0_KEY:tls/placeholder-server.key}
      trust-store:
        pem:
          certs: ${QUARKUS_TLS_BRIDGE_TRUST_STORE_PEM_CERTS:tls/placeholder-ca.pem}
  native:
    resources:
      includes:
        - application.yml
        - tls/placeholder-ca.pem
        - tls/placeholder-server.pem
        - tls/placeholder-server.key
        - META-INF/services/jakarta.xml.ws.spi.Provider
        - META-INF/services/jakarta.activation.spi.MailcapRegistryProvider
        - META-INF/services/jakarta.activation.spi.MimeTypeRegistryProvider
        - META-INF/services/javax.wsdl.factory.WSDLFactory
        - META-INF/cxf/bus-extensions.txt
        - META-INF/cxf/**
        - META-INF/wsdl/**
    additional-build-args:
      - "-H:+AllowVMInspection"
      - "--initialize-at-run-time=org.apache.cxf.attachment.AttachmentUtil"
      - "--initialize-at-run-time=org.apache.wss4j.common.saml.builder.SAML1ComponentBuilder"
      - "--initialize-at-run-time=org.apache.wss4j.common.saml.builder.SAML2ComponentBuilder"
      - "--initialize-at-run-time=org.apache.wss4j.common.saml.SamlAssertionWrapper"
      - "--initialize-at-run-time=org.opensaml.core.xml.config.XMLObjectProviderRegistry"
      - "--initialize-at-run-time=org.apache.cxf.interceptor.FIStaxInInterceptor"
      - "--initialize-at-run-time=org.apache.cxf.interceptor.FIStaxOutInterceptor"
      - "--initialize-at-run-time=org.apache.cxf.ws.security.trust.AbstractSTSClient"

cxf:
  address: ${CXF_ADDRESS:}
  connection:
    timeout:
      ms: ${CXF_CONNECTION_TIMEOUT_MS:30000}
  max:
    concurrent:
      requests: ${CXF_MAX_CONCURRENT_REQUESTS:100}
  consumer:
    timeout:
      ms: ${CXF_CONSUMER_TIMEOUT_MS:60000}

"%test":
  quarkus:
    http:
      ssl-port: -1
      insecure-requests: enabled
      ssl:
        client-auth: NEVER
    grpc:
      server:
        plain-text: true
        use-separate-server: true
    tls:
      bridge:
        key-store:
          pem:
            "0":
              cert: tls/test-server.pem
              key: tls/test-server.key
        trust-store:
          pem:
            certs: tls/test-ca.pem
