// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PredicateBlock } from "./PredicateBlock";

export type AggregateData = { header: string, correlation_key: string | null, completion_size: number | null, completion_timeout_ms: bigint | null, completion_predicate: PredicateBlock | null, strategy: string, max_buckets: number | null, 
/**
 * Upper bound on exchanges buffered inside one correlation bucket
 * (audit 2026-08-31, F6-2). Absent = builder default (10_000).
 */
max_bucket_size: number | null, bucket_ttl_ms: bigint | null, force_completion_on_stop: boolean | null, discard_on_timeout: boolean | null, };
