// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePeekStaleBody } from "./CachePeekStaleBody";

/**
 * Cache Peek Stale step — returns cached data even if TTL has expired.
 */
export type CachePeekStaleStep = { cache_peek_stale: CachePeekStaleBody, };
