// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheStatsBody } from "./CacheStatsBody";

/**
 * Cache Stats step — emits the repository stats as a JSON body.
 */
export type CacheStatsStep = { cache_stats: CacheStatsBody, };
