// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CachePeekStaleBody = { 
/**
 * Name of the registered CacheRepository (optional; defaults to system default).
 */
repository: string | null, 
/**
 * Simple-language expression for the cache key to peek.
 */
key: string, 
/**
 * On-miss policy: `"stop"` (default) or `"continue"`. Invalid values fail YAML
 * conversion (named value) and compile (canonical/programmatic path).
 * `null` is valid and means the default.
 */
on_miss: string | null, };
