// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheClearBody } from "./CacheClearBody";

/**
 * Cache Clear step — removes all entries from a CacheRepository.
 */
export type CacheClearStep = { cache_clear: CacheClearBody, };
