// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheClearBody = { 
/**
 * Name of the registered CacheRepository (optional; defaults to system default).
 */
repository: string | null, };
