// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheInvalidateBody } from "./CacheInvalidateBody";

/**
 * Cache Invalidate step — removes an entry from a CacheRepository.
 */
export type CacheInvalidateStep = { cache_invalidate: CacheInvalidateBody, };
