// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheBody } from "./CacheBody";

/**
 * Cache EIP step — puts/stores an exchange result in a `CacheRepository`.
 *
 * Short-hand (`cache: "redis-cache"`) uses the URI directly as repository
 * name. Full form (`cache: { repository: ..., key: ..., ... }`) supplies the
 * full configuration with an `on_miss` sub-pipeline.
 */
export type CacheStep = { cache: CacheBody, };
