// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheInvalidateBody = { 
/**
 * Name of the registered CacheRepository (optional; defaults to system default).
 */
repository: string | null, 
/**
 * Simple-language expression for the exact cache key to invalidate.
 * Mutually exclusive with `key_prefix` (exactly one of the two).
 */
key: string | null, 
/**
 * Simple-language expression for the namespace prefix to invalidate.
 * Mutually exclusive with `key` (exactly one of the two).
 */
key_prefix: string | null, };
