// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type CacheConfig = { 
/**
 * Name of the registered CacheRepository (optional; defaults to system default).
 */
repository: string | null, 
/**
 * Simple-language expression for the cache key.
 */
key: string, 
/**
 * Optional TTL expression/"duration string" (e.g. "60s", "5m").
 */
ttl: string | null, 
/**
 * Maximum bytes per cache entry (optional).
 */
max_entry_bytes: number | null, 
/**
 * Coalesce concurrent misses on the same key into a single `on_miss` run
 * (singleflight). Absent/null means `false`.
 */
coalesce_misses: boolean | null, 
/**
 * Child sub-pipeline executed on cache miss.
 */
on_miss: Array<RouteDslStep>, };
