// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalCircuitBreakerSpec } from "./CanonicalCircuitBreakerSpec";
import type { CanonicalConcurrencySpec } from "./CanonicalConcurrencySpec";
import type { CanonicalStepSpec } from "./CanonicalStepSpec";

export type CanonicalRouteSpec = { 
/**
 * Stable minimal route representation for runtime command registration.
 *
 * Scope notes:
 * - This is intentionally a partial model and does not mirror every `BuilderStep`.
 * - Version 2 adds: auto_startup, startup_order, concurrency.
 * - Still excluded: error_handler, unit_of_work. These are set to defaults
 *   when compiling from canonical.
 * - Round-trip (YAML → Canonical → YAML) loses these fields.
 * - Advanced EIPs continue to use the existing RouteDefinition/BuilderStep path.
 */
route_id: string, from: string, steps: Array<CanonicalStepSpec>, circuit_breaker: CanonicalCircuitBreakerSpec | null, auto_startup: boolean | null, startup_order: number | null, concurrency: CanonicalConcurrencySpec | null, version: number, };
