// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalStepSpec } from "./CanonicalStepSpec";
import type { LanguageExpressionDef } from "./LanguageExpressionDef";

export type CanonicalWhenSpec = { predicate: LanguageExpressionDef, steps: Array<CanonicalStepSpec>, };
