// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalCircuitBreakerSpec } from "./CanonicalCircuitBreakerSpec";
import type { CanonicalStepSpec } from "./CanonicalStepSpec";

export type CanonicalRouteSpec = { 
/**
 * Stable minimal route representation for runtime command registration.
 *
 * Scope note (v1):
 * - This is intentionally a partial model and does not mirror every `BuilderStep`.
 * - Not included in v1: auto_startup, startup_order, concurrency, error_handler,
 *   unit_of_work. These are set to defaults when compiling from canonical.
 * - Round-trip (YAML → Canonical → YAML) loses these fields.
 * - Advanced EIPs continue to use the existing RouteDefinition/BuilderStep path.
 */
route_id: string, from: string, steps: Array<CanonicalStepSpec>, circuit_breaker: CanonicalCircuitBreakerSpec | null, version: number, };
