// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CanonicalCircuitBreakerSpec = { failure_threshold: number, open_duration_ms: number, };
