// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CanonicalConcurrencySpec = { "mode": "sequential" } | { "mode": "concurrent", max: number, };
