// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalAggregateStrategySpec } from "./CanonicalAggregateStrategySpec";

export type CanonicalAggregateSpec = { header: string, completion_size: number | null, completion_timeout_ms: number, correlation_key: string | null, force_completion_on_stop: boolean | null, discard_on_timeout: boolean | null, strategy: CanonicalAggregateStrategySpec, max_buckets: number | null, bucket_ttl_ms: number, };
