// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageExpressionDef } from "./LanguageExpressionDef";
import type { StreamSplitConfig } from "./StreamSplitConfig";

export type CanonicalSplitExpressionSpec = "body_lines" | "body_json_array" | { "language": LanguageExpressionDef } | { "stream": StreamSplitConfig };
