// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalAggregateSpec } from "./CanonicalAggregateSpec";
import type { CanonicalSplitAggregationSpec } from "./CanonicalSplitAggregationSpec";
import type { CanonicalSplitExpressionSpec } from "./CanonicalSplitExpressionSpec";
import type { CanonicalWhenSpec } from "./CanonicalWhenSpec";
import type { LanguageExpressionDef } from "./LanguageExpressionDef";

export type CanonicalStepSpec = { "step": "to", "config": { uri: string, } } | { "step": "log", "config": { message: string, } } | { "step": "wire_tap", "config": { uri: string, } } | { "step": "script", "config": { expression: LanguageExpressionDef, } } | { "step": "filter", "config": { predicate: LanguageExpressionDef, steps: Array<CanonicalStepSpec>, } } | { "step": "choice", "config": { whens: Array<CanonicalWhenSpec>, otherwise: Array<CanonicalStepSpec> | null, } } | { "step": "split", "config": { expression: CanonicalSplitExpressionSpec, aggregation: CanonicalSplitAggregationSpec, parallel: boolean, parallel_limit: number | null, stop_on_exception: boolean, steps: Array<CanonicalStepSpec>, } } | { "step": "aggregate", "config": CanonicalAggregateSpec } | { "step": "stop" } | { "step": "delay", "config": { delay_ms: number, dynamic_header: string | null, } } | { "step": "cache", "config": { repository: string | null, key: string, ttl: string | null, max_entry_bytes: number | null, 
/**
 * Coalesce concurrent misses on the same key into a single `on_miss`
 * run. Absent/null means `false`.
 */
coalesce_misses?: boolean | null, on_miss: Array<CanonicalStepSpec>, } } | { "step": "cache_invalidate", "config": { repository: string | null, 
/**
 * Exact key to invalidate (simple-language expression).
 */
key?: string | null, 
/**
 * Namespace prefix to invalidate (simple-language expression).
 */
key_prefix?: string | null, } } | { "step": "cache_clear", "config": { repository: string | null, } } | { "step": "cache_stats", "config": { repository: string | null, } } | { "step": "cache_peek_stale", "config": { repository: string | null, key: string, 
/**
 * On-miss policy: `"stop"` (default) or `"continue"`. Absent/null means `"stop"`.
 */
on_miss?: string | null, } };
