// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalAggregateSpec } from "./CanonicalAggregateSpec";
import type { CanonicalSplitAggregationSpec } from "./CanonicalSplitAggregationSpec";
import type { CanonicalSplitExpressionSpec } from "./CanonicalSplitExpressionSpec";
import type { CanonicalWhenSpec } from "./CanonicalWhenSpec";
import type { LanguageExpressionDef } from "./LanguageExpressionDef";

export type CanonicalStepSpec = { "step": "to", "config": { uri: string, } } | { "step": "log", "config": { message: string, } } | { "step": "wire_tap", "config": { uri: string, } } | { "step": "script", "config": { expression: LanguageExpressionDef, } } | { "step": "filter", "config": { predicate: LanguageExpressionDef, steps: Array<CanonicalStepSpec>, } } | { "step": "choice", "config": { whens: Array<CanonicalWhenSpec>, otherwise: Array<CanonicalStepSpec> | null, } } | { "step": "split", "config": { expression: CanonicalSplitExpressionSpec, aggregation: CanonicalSplitAggregationSpec, parallel: boolean, parallel_limit: number | null, stop_on_exception: boolean, steps: Array<CanonicalStepSpec>, } } | { "step": "aggregate", "config": CanonicalAggregateSpec } | { "step": "stop" } | { "step": "delay", "config": { delay_ms: number, dynamic_header: string | null, } };
