// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExceptionDisposition } from "./ExceptionDisposition";
import type { RouteDslStep } from "./RouteDslStep";

export type CatchClauseData = { exception: Array<string> | null, when: string | null, on_when: string | null, disposition: ExceptionDisposition, steps: Array<RouteDslStep>, };
