// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PredicateBlock } from "./PredicateBlock";
import type { RouteDslStep } from "./RouteDslStep";

export type ChoiceData = { when: Array<PredicateBlock>, otherwise: Array<RouteDslStep> | null, };
