// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extraction source for a route's credential, as declared in YAML.
 *
 * Accepted forms: `authorization_header` (bare string),
 * `{ query_param: { param: token } }`, `{ cookie: { name: session } }`,
 * `{ header: { name: X-API-Key } }`. The field values are the user-declared
 * parameter/cookie/header names; they must be non-empty after trimming and,
 * for `header`, a valid RFC 9110 token (validated at load time in `yaml.rs`).
 */
export type CredentialSourceDsl = "authorization_header" | { "query_param": { param: string, } } | { "cookie": { name: string, } } | { "header": { name: string, } };
