// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatchClauseData } from "./CatchClauseData";
import type { FinallyData } from "./FinallyData";
import type { RouteDslStep } from "./RouteDslStep";

export type DoTryData = { steps: Array<RouteDslStep>, catch: Array<CatchClauseData>, finally: FinallyData | null, };
