// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Disposition for an exception handler or catch clause (ADR-0019).
 *
 * # YAML casing
 *
 * serde uses `lowercase` casing: `handled`, `propagate`, `continued`.
 *
 * # Default divergence
 *
 * `ExceptionDisposition::default()` returns `Propagate` (first variant per `#[derive(Default)]`),
 * but the YAML + builder layers default to `Handled` for doTry catch clauses
 * (via `default_handled_disposition()` in `camel-dsl/src/route_ast.rs` and the `DoCatchBuilder::do_catch_exception` constructor).
 * Direct struct construction should explicitly set disposition rather than relying on `Default`.
 */
export type ExceptionDisposition = "propagate" | "handled" | "continued";
