// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PredicateBlock } from "./PredicateBlock";

export type FilterStep = { filter: PredicateBlock, };
