// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A language expression/predicate reference resolved by the runtime.
 */
export type LanguageExpressionDef = { language: string, source: string, };
