// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type LoadBalanceData = { strategy: string, distribution_ratio: string | null, steps: Array<RouteDslStep>, };
