// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogMessageData } from "./LogMessageData";

export type LogConfig = { 
/**
 * The log message. Can be a plain string literal or a nested expression object.
 */
message: LogMessageData, level: string | null, };
