// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogMessageExpr } from "./LogMessageExpr";

/**
 * The `message` field inside a `log: { message: ... }` config block.
 * Either a bare string literal or a value-source expression (simple, rhai, language+source).
 */
export type LogMessageData = string | LogMessageExpr;
