// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopWhileExpr } from "./LoopWhileExpr";
import type { RouteDslStep } from "./RouteDslStep";

export type LoopFullConfig = { 
/**
 * Fixed iteration count. Mutually exclusive with `while`.
 */
count: number | null, 
/**
 * While condition — expression-only (no nested steps).
 */
while: LoopWhileExpr | null, steps: Array<RouteDslStep>, };
