// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Expression-only predicate for loop while condition.
 */
export type LoopWhileExpr = { language: string | null, source: string | null, simple: string | null, rhai: string | null, jsonpath: string | null, xpath: string | null, };
