// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type MulticastData = { parallel: boolean, parallel_limit: number | null, stop_on_exception: boolean, timeout_ms: bigint | null, aggregation: string, steps: Array<RouteDslStep>, };
