// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MulticastData } from "./MulticastData";

export type MulticastStep = { multicast: MulticastData, };
