// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type PredicateBlock = { language: string | null, source: string | null, simple: string | null, rhai: string | null, jsonpath: string | null, xpath: string | null, steps: Array<RouteDslStep>, };
