// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipientListData } from "./RecipientListData";

export type RecipientListStep = { recipient_list: RecipientListData, };
