// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipientListData = { simple: string | null, rhai: string | null, language: string | null, source: string | null, delimiter: string, parallel: boolean, parallel_limit: number | null, stop_on_exception: boolean, strategy: string | null, };
