// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslRedeliveryPolicy } from "./RouteDslRedeliveryPolicy";
import type { RouteDslStep } from "./RouteDslStep";

export type RouteDslOnException = { kind: string | null, message_contains: string | null, retry: RouteDslRedeliveryPolicy | null, steps: Array<RouteDslStep>, handled: boolean | null, continued: boolean | null, };
