// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslPermissionPolicy } from "./RouteDslPermissionPolicy";

export type RouteDslSecurityPolicy = { roles: Array<string> | null, scopes: Array<string> | null, all_required: boolean | null, ref: string | null, wasm: string | null, config: { [key in string]: string } | null, permission: RouteDslPermissionPolicy | null, };
