// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslCircuitBreaker } from "./RouteDslCircuitBreaker";
import type { RouteDslErrorHandler } from "./RouteDslErrorHandler";
import type { RouteDslSecurityPolicy } from "./RouteDslSecurityPolicy";
import type { RouteDslStep } from "./RouteDslStep";

export type RouteDslRoute = { id: string, from: string, steps: Array<RouteDslStep>, auto_startup: boolean, startup_order: number, sequential: boolean, concurrent: number | null, error_handler: RouteDslErrorHandler | null, circuit_breaker: RouteDslCircuitBreaker | null, security_policy: RouteDslSecurityPolicy | null, on_complete: string | null, on_failure: string | null, };
