// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TLS certificate and private-key paths declared by an MCP DSL server.
 */
export type RouteDslMcpTlsConfig = { 
/**
 * PEM-encoded server certificate chain.
 */
cert_path: string, 
/**
 * PEM-encoded server private key.
 */
key_path: string, };
