// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request to instantiate a template with concrete parameter values.
 */
export type RouteDslTemplatedRoute = { route_template_ref: string, 
/**
 * Optional explicit route id for the resulting instance.
 */
route_id: string | null, 
/**
 * Concrete parameter values keyed by parameter name.
 */
parameters: { [key in string]: string }, };
