// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single parameter that a route template accepts.
 */
export type RouteDslTemplateParameter = { 
/**
 * The parameter name (used inside `{{name}}` placeholders).
 */
name: string, 
/**
 * Optional default value used when the caller does not supply one.
 */
default_value: string | null, 
/**
 * Optional human-readable description.
 */
description: string | null, };
