// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslMcpTlsConfig } from "./RouteDslMcpTlsConfig";
import type { RouteDslSecurityPolicy } from "./RouteDslSecurityPolicy";

/**
 * Server-role (Consumer) declaration for one named MCP server inside a
 * `mcp:` block.
 *
 * The block owns its listener configuration the way `rest:` does (spec: MCP
 * listener ownership): `bind` always, and `tls`/`max_tools`/`max_resources`
 * when declared, are lowered onto every route of the block as
 * `mcp.declared.*` endpoint parameters and ARE the runtime values for
 * listener construction/lookup. TOML `mcp.servers.<name>` must still carry
 * the entry (the `name` MUST match a `mcp.servers.<name>` key or consumer
 * start fails) and remains the source for keys with no DSL counterpart
 * (`allowed_hosts`, `security_policy`); a key declared by BOTH sides with
 * different values fails consumer start with an error naming both sources —
 * no DSL field is silently ignored, and silence is never a disagreement
 * (a cap declared by one side only is that side's value).
 * The `security_policy` field is a real `RouteDslSecurityPolicy` (parse-time
 * validated, mirroring the route field) and it DOES flow to the lowered
 * consumer routes — enforcement is route-level (camel-api `SecurityPolicy`),
 * the same mechanism camel-http routes use.
 */
export type RouteDslMcpServer = { 
/**
 * Name of the server (referenced by lowered `mcp:<name>/...` routes).
 */
name: string, 
/**
 * Streamable-HTTP listen address (IP:port literal).
 */
bind: string, 
/**
 * Optional TLS configuration.
 */
tls: RouteDslMcpTlsConfig | null, 
/**
 * Route-level authorization policy, propagated to every lowered route
 * (tools AND resources). Evaluated per request against the carried
 * HTTP headers; absent means no route-level policy (the TOML
 * `security_policy` presence gate still applies fail-closed).
 */
security_policy: RouteDslSecurityPolicy | null, 
/**
 * Maximum number of tools this server may register (`None` when the
 * block declares no cap — the runtime default then applies, and the
 * lowering emits no `max_tools` parameter so a TOML-declared cap is
 * kept).
 */
max_tools: number | null, 
/**
 * Maximum number of resources this server may register (`None` when
 * the block declares no cap).
 */
max_resources: number | null, };
