// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslPermissionPolicy } from "./RouteDslPermissionPolicy";

export type RouteDslSecurityPolicy = { roles: Array<string> | null, scopes: Array<string> | null, all_required: boolean | null, 
/**
 * When `true`, the policy accepts an already-populated
 * `camel.auth.principal` exchange property when no Bearer token is
 * present. Default `false` (fail-closed) — the principal must come
 * from token validation. See H1 in
 * `docs/superpowers/specs/v1-sec-stabilization-spec.md`.
 */
trust_upstream_principal: boolean | null, ref: string | null, wasm: string | null, config: { [key in string]: string } | null, permission: RouteDslPermissionPolicy | null, };
