// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteDslRedeliveryPolicy = { max_attempts: number, initial_delay_ms: bigint, multiplier: number, max_delay_ms: bigint, jitter_factor: number, handled_by: string | null, };
