// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslPermissionContext } from "./RouteDslPermissionContext";
import type { RouteDslPermissionValueSource } from "./RouteDslPermissionValueSource";

export type RouteDslPermissionPolicy = { policy: string, resource: RouteDslPermissionValueSource | null, action: RouteDslPermissionValueSource | null, scopes: Array<string> | null, context: RouteDslPermissionContext | null, cache_ttl_secs: bigint | null, cache_negative_ttl_secs: bigint | null, };
