// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type RouteDslCircuitBreaker = { failure_threshold: number, open_duration_ms: bigint, fallback: Array<RouteDslStep>, };
