// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslOnException } from "./RouteDslOnException";
import type { RouteDslRedeliveryPolicy } from "./RouteDslRedeliveryPolicy";

export type RouteDslErrorHandler = { dead_letter_channel: string | null, retry: RouteDslRedeliveryPolicy | null, on_exceptions: Array<RouteDslOnException> | null, };
