// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslRestBinding } from "./RouteDslRestBinding";
import type { RouteDslRestResponse } from "./RouteDslRestResponse";
import type { RouteDslStep } from "./RouteDslStep";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single REST operation (identified by its `method` field).
 */
export type RouteDslRestOperation = { 
/**
 * HTTP method for this operation (e.g. `GET`, `post`). Case-insensitive;
 * validated against the known-verb set during lowering.
 */
method: string, 
/**
 * Sub-path relative to the parent RouteDslRest path.
 */
path: string, 
/**
 * Optional unique identifier for this operation.
 */
operation_id: string | null, 
/**
 * Endpoint URI to route matching requests to (e.g. `bean:userService`).
 */
to: string | null, 
/**
 * Child sub-pipeline steps.
 */
steps: Array<RouteDslStep>, 
/**
 * Default content-type consumed by this operation.
 */
consumes: string, 
/**
 * Default content-type produced by this operation.
 */
produces: string, 
/**
 * Optional binding mode: `json` (default) or `raw`. Never inferred from media type.
 */
binding: RouteDslRestBinding | null, 
/**
 * Expected success HTTP status code (e.g. 200, 201).
 */
success_status: number | null, 
/**
 * Optional request body schema.
 */
request_schema: JsonValue | null, 
/**
 * Response definition.
 */
response: RouteDslRestResponse | null, 
/**
 * Optional description of this operation.
 */
description: string | null, 
/**
 * Additional operation parameters.
 */
parameters: { [key in string]: JsonValue }, };
