// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binding mode for a REST operation: automatic JSON data-format binding
 * (default) or raw passthrough with no automatic binding steps.
 */
export type RouteDslRestBinding = "json" | "raw";
