// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response definition for a REST operation.
 */
export type RouteDslRestResponse = { 
/**
 * Optional response description.
 */
description: string | null, 
/**
 * Response body schema.
 */
schema: JsonValue | null, 
/**
 * Response headers map.
 */
headers: { [key in string]: JsonValue }, };
