// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslRestOperation } from "./RouteDslRestOperation";
import type { RouteDslSecurityPolicy } from "./RouteDslSecurityPolicy";

/**
 * A top-level REST block (`rest:` in YAML/JSON).
 */
export type RouteDslRest = { 
/**
 * Listen host address.
 */
host: string, 
/**
 * Listen port.
 */
port: number, 
/**
 * Base path for all operations in this block (e.g. `/api/users`).
 */
path: string, 
/**
 * Route-level authorization policy applied to EVERY operation in this
 * block (`unify-transport-auth`, Task 2.10). Lowering copies it onto
 * each lowered route, so enforcement is route-level — the same
 * mechanism `http:` routes use. Same surface and load-time validation
 * as `RouteDslRoute.security_policy` (the lowered routes run the shared
 * conversion in `yaml.rs`). Absent means the lowered routes carry no
 * policy (Public under the kernel gate).
 */
security_policy: RouteDslSecurityPolicy | null, 
/**
 * Operations for this block, each carrying its own HTTP method.
 */
operations: Array<RouteDslRestOperation>, };
