// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission value source for a route permission: exactly one of `literal`,
 * `header`, or `property` must be non-null (the other two absent or null).
 * Runtime anchor: `yaml_source_to_value_source` in `camel-dsl/src/yaml.rs`
 * (rc-gddb2, reject-on-ambiguity).
 */
export type RouteDslPermissionValueSource = { literal: string | null, header: string | null, property: string | null, };
