// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialSourceDsl } from "./CredentialSourceDsl";
import type { RouteDslPermissionPolicy } from "./RouteDslPermissionPolicy";

export type RouteDslSecurityPolicy = { roles: Array<string> | null, scopes: Array<string> | null, all_required: boolean | null, ref: string | null, wasm: string | null, config: { [key in string]: string } | null, permission: RouteDslPermissionPolicy | null, 
/**
 * Declared extraction sources for the route's credential, in order.
 * Absent → compile-time default `[authorization_header]`. Valid only with
 * the `roles`/`scopes` forms (validated at load time in `yaml.rs`).
 */
credential_sources: Array<CredentialSourceDsl> | null, 
/**
 * Named authenticator provider to resolve the route's authenticator from
 * `SecurityCompileContext::providers`. Absent → sole provider (or legacy
 * single-authenticator) resolution. Valid only with the `roles`/`scopes`
 * forms (validated at load time in `yaml.rs`), mirroring
 * `credential_sources`.
 */
provider?: string | null, 
/**
 * Route-level audience override for the compiled security plan. When
 * present the plan's `audience_binding.audiences` uses these values
 * (issuers still come from the provider); when absent the resolved
 * provider's binding is copied verbatim. Valid only with the
 * `roles`/`scopes` forms (validated at load time in `yaml.rs`),
 * mirroring `provider`.
 */
audiences?: Array<string> | null, };
