// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutingSlipData } from "./RoutingSlipData";

export type RoutingSlipStep = { routing_slip: RoutingSlipData, };
