// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslMcpResource } from "./RouteDslMcpResource";
import type { RouteDslMcpServer } from "./RouteDslMcpServer";
import type { RouteDslMcpTool } from "./RouteDslMcpTool";

/**
 * A top-level MCP block (`mcp:` in YAML/JSON).
 */
export type RouteDslMcp = { 
/**
 * Named server (Consumer) declaration.
 */
server: RouteDslMcpServer, 
/**
 * Tools this server exposes.
 */
tools: Array<RouteDslMcpTool>, 
/**
 * Resources this server exposes.
 */
resources: Array<RouteDslMcpResource>, };
