// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutingSlipData = { simple: string | null, rhai: string | null, language: string | null, source: string | null, uri_delimiter: string, cache_size: number, ignore_invalid_endpoints: boolean, };
