// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single MCP resource declaration, carrying its MCP resource URI.
 */
export type RouteDslMcpResource = { 
/**
 * Resource name (referenced by the lowered `mcp:<server>/resource/<name>` route).
 */
name: string, 
/**
 * The MCP resource URI (operator config, e.g. `crm://customers`).
 */
uri: string, };
