// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single MCP tool declaration, carrying its input JSON Schema.
 */
export type RouteDslMcpTool = { 
/**
 * Tool name (referenced by the lowered `mcp:<server>/tool/<name>` route).
 */
name: string, 
/**
 * Input JSON Schema for the tool's arguments.
 */
input_schema: JsonValue, 
/**
 * Endpoint URI to route the tool call to (e.g. `direct:out`).
 */
to: string | null, 
/**
 * Child sub-pipeline steps.
 */
steps: Array<RouteDslStep>, };
