// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetHeaderData } from "./SetHeaderData";

export type SetHeaderStep = { set_header: SetHeaderData, };
