// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetPropertyData } from "./SetPropertyData";

export type SetPropertyStep = { set_property: SetPropertyData, };
