// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type SetPropertyData = { name: string, value: JsonValue | null, language: string | null, source: string | null, simple: string | null, rhai: string | null, jsonpath: string | null, xpath: string | null, };
