// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";
import type { SplitExpressionYaml } from "./SplitExpressionYaml";
import type { StreamConfigYaml } from "./StreamConfigYaml";

export type SplitData = { expression: SplitExpressionYaml | null, aggregation: string, parallel: boolean, parallel_limit: number | null, stop_on_exception: boolean, steps: Array<RouteDslStep>, streaming: boolean, stream: StreamConfigYaml | null, };
