// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitExpressionConfig } from "./SplitExpressionConfig";

export type SplitExpressionYaml = string | SplitExpressionConfig;
