// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitData } from "./SplitData";

export type SplitStep = { split: SplitData, };
