// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamConfigYaml = { format: string | null, max_record_bytes: number | null, batch_size: number | null, chunk_size: number | null, };
