// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamCacheBody } from "./StreamCacheBody";

export type StreamCacheStep = { stream_cache: StreamCacheBody, };
