// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The streaming format to use when splitting a stream body.
 */
export type StreamSplitFormat = "auto" | "ndjson" | "lines" | "chunks" | "zip";
