// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamSplitFormat } from "./StreamSplitFormat";

/**
 * Configuration for splitting a streaming body into fragments.
 *
 * Controls how the stream splitter processes the body, including format
 * detection, sizing limits, and metadata propagation.
 */
export type StreamSplitConfig = { 
/**
 * The streaming format to use.
 */
format: StreamSplitFormat, 
/**
 * Maximum size (in bytes) of a single record or chunk.
 */
max_record_bytes: number, 
/**
 * Number of records/chunks to collect into a single exchange batch.
 */
batch_size: number, 
/**
 * Explicit chunk size in bytes (required when format is [`Chunks`](StreamSplitFormat::Chunks)).
 */
chunk_size: number | null, 
/**
 * Whether to include origin metadata in each fragment.
 */
include_origin: boolean, };
