// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThrottleData } from "./ThrottleData";

export type ThrottleStep = { throttle: ThrottleData, };
