// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDslStep } from "./RouteDslStep";

export type ThrottleData = { max_requests: number, period_secs: bigint, strategy: string | null, steps: Array<RouteDslStep>, };
