// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetBodyData } from "./SetBodyData";

/**
 * `transform:` step — alias for `set_body:`, reuses all SetBodyData types.
 */
export type TransformStep = { transform: SetBodyData, };
