// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UnmarshalStep = { unmarshal: string, 
/**
 * Optional JSON Schema. When present, the compiled UnmarshalService is
 * wrapped with a `JsonSchemaValidateService` that returns
 * `CamelError::ValidationError` (→ 400 Bad Request) on a mismatch.
 * Only effective when the format parses to `Body::Json` (currently `json`
 * is the only format that produces JSON in v1).
 */
schema: JsonValue | null, config: JsonValue | null, };
