[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y cmake pkg-config libcurl4-openssl-dev:arm64 libssl-dev:arm64 libsasl2-dev:arm64 zlib1g-dev:arm64 libzstd-dev:arm64 libxml2-dev:arm64",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["RUSTFLAGS"]
volumes = []
