[package]
name = "rabbitmq-example"
description = "RabbitMQ component example for rust-camel (local Docker fixture)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camel-api.workspace = true
camel-core.workspace = true
camel-builder.workspace = true
camel-component-rabbitmq = { workspace = true }
camel-component-timer.workspace = true
camel-component-log.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true

[lints]
workspace = true
