quarkus:
  grpc:
    server:
      port: 9090
      use-separate-server: false
      plain-text: false
  http:
    port: -1
    ssl-port: ${QUARKUS_HTTP_SSL_PORT:8443}
    insecure-requests: disabled
    ssl:
      client-auth: REQUIRED
    tls-configuration-name: bridge
  tls:
    bridge:
      key-store:
        pem:
          "0":
            cert: ${QUARKUS_TLS_BRIDGE_KEY_STORE_PEM_0_CERT:tls/placeholder-server.pem}
            key: ${QUARKUS_TLS_BRIDGE_KEY_STORE_PEM_0_KEY:tls/placeholder-server.key}
      trust-store:
        pem:
          certs: ${QUARKUS_TLS_BRIDGE_TRUST_STORE_PEM_CERTS:tls/placeholder-ca.pem}
  native:
    resources:
      includes:
        - tls/placeholder-ca.pem
        - tls/placeholder-server.pem
        - tls/placeholder-server.key
    additional-build-args:
      - "-H:+AllowVMInspection"

"%test":
  quarkus:
    http:
      ssl-port: -1
      insecure-requests: enabled
      ssl:
        client-auth: NEVER
    grpc:
      server:
        plain-text: true
        use-separate-server: true
    tls:
      bridge:
        key-store:
          pem:
            "0":
              cert: tls/test-server.pem
              key: tls/test-server.key
        trust-store:
          pem:
            certs: tls/test-ca.pem
