[book]
authors = ["rust-camel contributors"]
language = "en"
src = "src"
title = "rust-camel Guide"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/kennycallado/rust-camel"
site-url = "/rust-camel/docs/"

[preprocessor.adrs]
command = "python3 scripts/mdbook-adrs.py"

[output.html.fold]
enable = true
level = 1
