name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  call-release-matrix:
    uses: ./.github/workflows/release-matrix.yml
    with:
      publish: true
    secrets: inherit
